server:
  port: 8080
  servlet:
    context-path: /ap-saree-store

sms:
  gateway:
    api-key: Bm7G6zho0bkjlHWgK5FNpV9UTu2y4qQiXseMZPrISfx3dLCOt11pZqKe8lIkM9jUSWhHXoywRsEd3g6F

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: akhil.chinni.24@gmail.com
    password: qfup jker jksz cubi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
            required: false
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000